version: '3.8'

services:
  mausoleum:
    image: mausoleum
    working_dir: /app
    volumes:
      - .:/app
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: ["/app/entrypoint.sh"]
