name: Publish Python distribution to PyPI

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install build tools
      run: python -m pip install --upgrade build

    - name: Build package
      run: python -m build --sdist --wheel --outdir dist/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest